version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: eclinic_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: AIATIC
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=configuracion.settings
      - DATABASE_URL=postgres://postgres:AIATIC@db:5432/eclinic_db

volumes:
  postgres_data:
